### ISSUE TITLE
希望推出反降重系统

### ISSUE THREAD

**Issue by PupilStudio** [ASoulCnki/ASoulCnki#37]
降重 1.0 : 向小作文内添加无意义的标点；

2.0 : 添加零宽空格。

想法：评论过滤一遍，特殊符号和标点符号去掉另存一份，查重时同时匹配两者。

2.0 Hack代码付 https://www.luogu.com.cn/paste/zuujw8jt

效果图如下

![](https://cdn.luogu.com.cn/upload/image_hosting/rn3migrt.png)

**Comment by PupilStudio** [comment]
图片链接

[](https://cdn.luogu.com.cn/upload/image_hosting/rn3migrt.png)

**Comment by PupilStudio** [comment]
图片链接

[](https://cdn.luogu.com.cn/upload/image_hosting/rn3migrt.png)

**Comment by PupilStudio** [comment]
[图片链接](https://cdn.luogu.com.cn/upload/image_hosting/rn3migrt.png)

**Comment by yllhwa** [comment]
7/30的时候就发现了，但是一直没有提上日程😂
既然都提到了就马上加！

**Comment by sparanoid** [comment]
这种感觉不属于标准的「降重」范畴了吧，更像是增加了一层混淆。

反而觉得可以在查重的时候去掉这类混淆字符，增加查重率

**Comment by PupilStudio** [comment]
> 这种感觉不属于标准的「降重」范畴了吧，更像是增加了一层混淆。
> 
> 反而觉得可以在查重的时候去掉这类混淆字符，增加查重率

确实，我想法就是这个

**Comment by yllhwa** [comment]
后端最新的代码已经anti了这种降重方式了，具体代码是:
```java
s = s.replaceAll("\\p{Cf}","");
s = s.replaceAll("/[\\u200b-\\u200f\\ufeff\\u202a-\\u202e]/g","");
```
