### ISSUE TITLE
请求共享已爬取数据

### ISSUE THREAD

**Issue by infinityedge01** [ASoulCnki/ASoulCnki#40]
作者您好，我目前正在开发新的查重工具，希望可以共享一下所有已经爬取的评论数据库捏

**Comment by ch3cknull** [comment]
目前已公开的数据（至8月14日，从数据库导出的json），地址如下
https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view?usp=sharing

因为我们目前资源紧缺也都是用学生机，所以不会开放数据库连接

如果想获取实时性的数据，可以根据爬虫项目下 Deploy.md 自行搭建爬虫

目前爬虫的资源占用主要是mysql，我本人机器测试大约内存占用200M左右，可以试着搭建一下的

**Comment by ch3cknull** [comment]
另外请注意，如果搭建爬虫，JSON是8月14日的
由于在8月15日在数据库的 reply 表 新增了 类型为 int 的 uid 列，所以这一列在JSON中是缺失的

**Comment by infinityedge01** [comment]
感谢作者的分享，嘉门🙏
