### ISSUE TITLE
想问下目前版本 爬虫的数据是如何和后端项目共享数据的呢

### ISSUE THREAD

**Issue by BI1LQV** [ASoulCnki/ASoulCnki#50]
后端项目[部署文档](https://github.com/ASoulCnki/ASoulCnkiBackend/blob/master/README.md#21-%E4%BE%9D%E8%B5%96json%E6%96%87%E4%BB%B6%E8%BF%90%E8%A1%8C)提到文件`bilibili_cnki_reply.json`，目测应该是爬虫爬到的回复数据吧，但是这个爬虫项目貌似是把数据存到mysql里了，全仓库搜索`bilibili_cnki_reply.json`也没找到对应的代码，想问下这个json是如何生成的呢

**Comment by yllhwa** [comment]
你好，目前没有使用json文件，而是直接对接的数据库

对应后端配置文件为：
https://github.com/ASoulCnki/ASoulCnkiBackend/blob/master/src/main/resources/application-demo.yml

**Comment by ch3cknull** [comment]
JSON文件是在不方便搭建数据库的情况下使用的（JSON文件和数据库二选一），其实就是从数据库表导出的数据，如果考虑到实时性，还是建议连接数据库使用。

如果需要JSON文件，这里有一份去年8月份的，但是不确保能用，因为中途有写表的字段发生了变动

https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view

**Comment by BI1LQV** [comment]
感谢两位 已经跑通啦 回头有空去给后端那边readme提个pr优化一下

另外我跑这个爬虫的时候 遇到了一些小问题 记录在这个pr里 可以麻烦审一下嘛

https://github.com/ASoulCnki/ASoulCnki/pull/49
